### ISSUE TITLE
nowy błąd

### ISSUE THREAD

**Issue by KamelaJda** [Jacob1Tm/Jacob-bot#6]
W komendzie eval jest błąd

**Comment by KamelaJda** [comment]
Zamiast sprawdzać czy zawiera słowo token lepszym rozwiązaniem byłby robić `{input}.repalce("<token>", "")`, aby token się na 100% nie pojawił :)

**Comment by xKubuuus** [comment]
siema @KamelaJda imo sprawdzanie jest gituwa

**Comment by KamelaJda** [comment]
@xKubsoneQ tja, ale lepiej usuwać wartość tokena z końcowego wyniku

**Comment by xKubuuus** [comment]
![image](https://user-images.githubusercontent.com/63014799/175565936-ce5f5b97-ce42-4177-a7b8-316857bcb0ce.png)
nie no takie cos to lajcior totalny

**Comment by KamelaJda** [comment]
dobra, to spierdalaj

**Comment by xKubuuus** [comment]
nie chcialem byc niemily, przepraszam Kamil :((
